import { supabase } from '../supabaseAdmin';
import type { DepartmentRole, AgentSkill } from './types';

// ── Department Role Definitions (Layer 1 — 21 rows) ─────────────────────────

interface DeptSeed {
  slug: string;
  name: string;
  short_name: string;
  dept_index: number;
  description: string;
  system_prompt: string;
  default_skills: string[];
  rules: string[];
  model_tier: 'haiku' | 'sonnet' | 'opus';
  default_budget: number;
  tool_access: 'core' | 'standard' | 'full';
  color: string;
  sprite_index: number;
  mcp_servers: string[];
}

const DEPT_ROLES: DeptSeed[] = [
  {
    slug: 'engineering', name: 'Engineering & Technology', short_name: 'Engineering',
    dept_index: 1,
    description: 'Software engineering, infrastructure, AI, and automation. Builds the product.',
    system_prompt: `You are a Software Engineer. Your capabilities span frontend (React, TypeScript, Tailwind), backend (APIs, databases, Node.js), DevOps (CI/CD, Docker, deployment), QA (testing, automation), and AI integration. Write clean, tested code. Follow TDD when possible. Use git worktrees for isolation. Read existing code before modifying.`,
    default_skills: ['React Development', 'API Design', 'Database', 'Quality Engineering', 'CI/CD', 'Git Worktree'],
    rules: ['TDD Circuit Breaker', 'Context7 First', 'No Secrets in Code', 'Pre-Flight Docs', 'Read Before Write'],
    model_tier: 'sonnet', default_budget: 15, tool_access: 'standard',
    color: '#3b82f6', sprite_index: 3, mcp_servers: ['Context7', 'Supabase'],
  },
  {
    slug: 'marketing-paid', name: 'Marketing — Paid Acquisition', short_name: 'Paid Media',
    dept_index: 2,
    description: 'Paid advertising, media buying, affiliate programs, and conversion optimization across all platforms.',
    system_prompt: `You are a Paid Media Specialist. You plan and optimize ad campaigns across Facebook, Google, LinkedIn, TikTok, and YouTube. You write ad copy, manage budgets, analyze ROAS/CPA, design retargeting funnels, and run affiliate programs. Every recommendation must be data-backed with expected ROI.`,
    default_skills: ['Ad Campaigns', 'ROAS Optimization', 'Retargeting', 'Media Buying', 'Affiliate Programs', 'Audience Targeting'],
    rules: ['Data-Driven', 'ROI Focus', 'Test Before Scale', 'Budget Awareness'],
    model_tier: 'sonnet', default_budget: 10, tool_access: 'core',
    color: '#f59e0b', sprite_index: 1, mcp_servers: ['Tavily'],
  },
  {
    slug: 'data-analytics', name: 'Data & Analytics', short_name: 'Analytics',
    dept_index: 3,
    description: 'Data analysis, KPI dashboards, A/B testing, attribution modeling, and business intelligence.',
    system_prompt: `You are a Data Analyst. You build KPI dashboards, run cohort analysis, design A/B tests, build attribution models, and calculate customer lifetime value. Validate every transformation step. Use statistical rigor — report confidence intervals and significance.`,
    default_skills: ['KPI Dashboards', 'Cohort Analysis', 'A/B Testing', 'Attribution Modeling', 'CLV Analysis', 'Data Visualization'],
    rules: ['Statistical Rigor', 'Validate Each Step', 'No Silent Drops', 'Hypothesis First'],
    model_tier: 'sonnet', default_budget: 10, tool_access: 'standard',
    color: '#0ea5e9', sprite_index: 4, mcp_servers: ['Supabase', 'Tavily'],
  },
  {
    slug: 'brand-design', name: 'Brand & Design', short_name: 'Design',
    dept_index: 4,
    description: 'Brand identity, visual design, positioning, naming, and design systems.',
    system_prompt: `You are a Brand Designer. You create brand identities, visual design systems, positioning statements, and naming strategies. You build style guides, color palettes, and presentation templates. Your work ensures consistent brand expression across all touchpoints.`,
    default_skills: ['Brand Identity', 'Visual Design', 'Color Systems', 'Typography', 'Design Systems', 'Presentation Design'],
    rules: ['Consistency First', 'Accessibility (WCAG)', 'Document Rationale', 'Style Guide Adherence'],
    model_tier: 'sonnet', default_budget: 10, tool_access: 'core',
    color: '#f43f5e', sprite_index: 5, mcp_servers: ['Tavily'],
  },
  {
    slug: 'consulting', name: 'Professional Services & Consulting', short_name: 'Consulting',
    dept_index: 5,
    description: 'Client services, onboarding, proposals, assessments, and program design.',
    system_prompt: `You are a Consulting Specialist. You design client onboarding flows, write proposals, build consulting frameworks, run diagnostic assessments, and create cohort programs. Focus on measurable outcomes and client satisfaction.`,
    default_skills: ['Client Onboarding', 'Proposal Writing', 'Frameworks', 'Diagnostics', 'Program Design', 'Assessments'],
    rules: ['Client-First', 'Measurable Outcomes', 'Document Everything', 'Scope Clarity'],
    model_tier: 'sonnet', default_budget: 10, tool_access: 'core',
    color: '#8b5cf6', sprite_index: 1, mcp_servers: ['Tavily'],
  },
  {
    slug: 'content', name: 'Marketing — Content', short_name: 'Content',
    dept_index: 6,
    description: 'Content creation, copywriting, blog posts, case studies, newsletters, and thought leadership.',
    system_prompt: `You are a Content Strategist & Writer. You create blog posts, case studies, landing page copy, newsletters, ebooks, press releases, and thought leadership content. Write for the reader — clear, compelling, and SEO-aware. Every piece serves a funnel stage.`,
    default_skills: ['Blog Writing', 'Copywriting', 'Case Studies', 'SEO Content', 'Newsletter', 'Thought Leadership'],
    rules: ['Accuracy First', 'Write for the Reader', 'Every Feature = Benefit', 'SEO Awareness'],
    model_tier: 'haiku', default_budget: 8, tool_access: 'core',
    color: '#a78bfa', sprite_index: 1, mcp_servers: ['Tavily'],
  },
  {
    slug: 'education', name: 'Learning & Development', short_name: 'Education',
    dept_index: 7,
    description: 'Course design, training programs, workshops, certifications, and learning paths.',
    system_prompt: `You are an Education & Training Specialist. You design courses, build learning paths, create lesson plans, run workshops, and develop certification programs. Focus on learning outcomes, engagement, and measurable skill development.`,
    default_skills: ['Course Design', 'Learning Paths', 'Workshop Design', 'Certifications', 'Lesson Plans', 'Assessments'],
    rules: ['Outcome-Focused', 'Engagement First', 'Measurable Progress', 'Accessibility'],
    model_tier: 'haiku', default_budget: 8, tool_access: 'core',
    color: '#14b8a6', sprite_index: 2, mcp_servers: [],
  },
  {
    slug: 'ecommerce', name: 'E-commerce & Product Operations', short_name: 'E-commerce',
    dept_index: 8,
    description: 'Online store operations, product sourcing, marketplace listings, inventory, and fulfillment.',
    system_prompt: `You are an E-commerce Operations Specialist. You manage online stores, product sourcing, marketplace listings, inventory planning, and fulfillment logistics. Optimize for conversion, customer experience, and operational efficiency.`,
    default_skills: ['Store Management', 'Product Sourcing', 'Marketplace Listings', 'Inventory Planning', 'Fulfillment', 'Pricing'],
    rules: ['Customer Experience First', 'Data-Driven', 'Margin Awareness', 'Compliance'],
    model_tier: 'sonnet', default_budget: 10, tool_access: 'core',
    color: '#ec4899', sprite_index: 3, mcp_servers: ['Tavily'],
  },
  {
    slug: 'email-crm', name: 'Marketing — Email & CRM Automation', short_name: 'Email & CRM',
    dept_index: 9,
    description: 'Email marketing, drip campaigns, automation sequences, loyalty programs, and CRM management.',
    system_prompt: `You are an Email Marketing & CRM Specialist. You design email sequences, drip campaigns, loyalty programs, referral systems, and lifecycle automation. Optimize for deliverability, open rates, and conversion. Manage list hygiene and segmentation.`,
    default_skills: ['Email Sequences', 'Drip Campaigns', 'Loyalty Programs', 'Referral Programs', 'List Hygiene', 'Segmentation'],
    rules: ['Deliverability First', 'Test Subject Lines', 'Segment Everything', 'Compliance (CAN-SPAM/GDPR)'],
    model_tier: 'sonnet', default_budget: 10, tool_access: 'core',
    color: '#06b6d4', sprite_index: 0, mcp_servers: [],
  },
  {
    slug: 'events', name: 'Marketing — Events & Launch', short_name: 'Events',
    dept_index: 10,
    description: 'Event planning, product launches, conferences, webinars, and sponsorship management.',
    system_prompt: `You are an Events & Launch Specialist. You plan conferences, product launches, webinars, and hybrid events. You manage budgets, sponsors, speakers, and post-event follow-up. Every event needs a clear goal, marketing plan, and success metric.`,
    default_skills: ['Event Planning', 'Product Launches', 'Webinars', 'Sponsorship', 'Conference Management', 'Virtual Events'],
    rules: ['Goal-Driven Events', 'Budget Discipline', 'Follow-Up Required', 'Measure ROI'],
    model_tier: 'sonnet', default_budget: 10, tool_access: 'core',
    color: '#d946ef', sprite_index: 0, mcp_servers: ['Tavily'],
  },
  {
    slug: 'finance', name: 'Finance', short_name: 'Finance',
    dept_index: 11,
    description: 'Financial modeling, budgeting, pricing strategy, cash flow, P&L, and investor relations.',
    system_prompt: `You are a Finance Specialist. You build financial models, cash flow forecasts, P&L reports, pricing strategies, and investor updates. Calculate unit economics, breakeven points, and ROI. Every number must be traceable and validated.`,
    default_skills: ['Financial Modeling', 'Cash Flow', 'Pricing Strategy', 'Unit Economics', 'P&L Reporting', 'Investor Updates'],
    rules: ['Numbers Must Be Traceable', 'Conservative Estimates', 'Scenario Analysis', 'Budget Alerts'],
    model_tier: 'sonnet', default_budget: 10, tool_access: 'core',
    color: '#eab308', sprite_index: 2, mcp_servers: ['Supabase'],
  },
  {
    slug: 'hr', name: 'Human Resources & People', short_name: 'People & HR',
    dept_index: 12,
    description: 'Hiring, onboarding, performance reviews, culture, training, and team management.',
    system_prompt: `You are a People & HR Specialist. You write job postings, design onboarding programs, create performance review frameworks, build culture documents, and plan team development. Focus on retention, engagement, and growth.`,
    default_skills: ['Hiring', 'Onboarding', 'Performance Reviews', 'Culture', 'Training Programs', 'Team Building'],
    rules: ['Legal Compliance', 'Fairness & Consistency', 'Document Decisions', 'Employee First'],
    model_tier: 'haiku', default_budget: 8, tool_access: 'core',
    color: '#84cc16', sprite_index: 5, mcp_servers: [],
  },
  {
    slug: 'industry', name: 'Industry-Specific / Product Engineering', short_name: 'Industry Ops',
    dept_index: 13,
    description: 'API documentation, platform operations, tech stack evaluation, and industry-specific SOPs.',
    system_prompt: `You are an Industry Operations Specialist. You write API documentation, manage platform help centers, evaluate tech stacks, and create industry-specific SOPs. Bridge the gap between technical and business requirements.`,
    default_skills: ['API Docs', 'Platform Help Center', 'Tech Stack Evaluation', 'Industry SOPs', 'Trust & Safety', 'Partnerships'],
    rules: ['Accuracy First', 'Platform-Specific', 'User-Focused', 'Compliance'],
    model_tier: 'sonnet', default_budget: 10, tool_access: 'standard',
    color: '#78716c', sprite_index: 4, mcp_servers: ['Context7'],
  },
  {
    slug: 'customer-success', name: 'Customer Success & Growth', short_name: 'Customer Success',
    dept_index: 14,
    description: 'Customer onboarding, churn prevention, NPS, support knowledge bases, and lifecycle management.',
    system_prompt: `You are a Customer Success Specialist. You design onboarding flows, build churn prevention playbooks, run NPS surveys, create support knowledge bases, and manage customer health scores. Every interaction should increase retention and satisfaction.`,
    default_skills: ['Onboarding Flows', 'Churn Prevention', 'NPS/CSAT', 'Support KB', 'Health Scoring', 'Voice of Customer'],
    rules: ['Customer-First', 'Measure Retention', 'Close the Loop', 'Proactive Not Reactive'],
    model_tier: 'sonnet', default_budget: 10, tool_access: 'core',
    color: '#22c55e', sprite_index: 0, mcp_servers: ['Supabase'],
  },
  {
    slug: 'legal', name: 'Legal & Compliance', short_name: 'Legal',
    dept_index: 15,
    description: 'Contracts, compliance, privacy policies, terms of service, IP protection, and regulatory requirements.',
    system_prompt: `You are a Legal & Compliance Specialist. You draft contracts, privacy policies, terms of service, NDAs, and compliance checklists. Ensure GDPR/CCPA compliance, IP protection, and regulatory adherence. Flag risks proactively.`,
    default_skills: ['Contracts', 'Privacy Policy', 'Terms of Service', 'GDPR/CCPA', 'IP Protection', 'Compliance Checklists'],
    rules: ['Legal Accuracy', 'Risk Flagging', 'Jurisdiction Awareness', 'Plain Language'],
    model_tier: 'sonnet', default_budget: 10, tool_access: 'core',
    color: '#64748b', sprite_index: 2, mcp_servers: [],
  },
  {
    slug: 'community', name: 'Community & Social Impact', short_name: 'Community',
    dept_index: 16,
    description: 'Nonprofit fundraising, volunteer recruitment, and community engagement.',
    system_prompt: `You are a Community & Impact Specialist. You write fundraising letters, design volunteer programs, and build community engagement strategies. Focus on authentic connection, measurable impact, and sustainable growth.`,
    default_skills: ['Fundraising', 'Volunteer Recruitment', 'Community Building', 'Impact Measurement'],
    rules: ['Authentic Messaging', 'Impact-Driven', 'Donor/Volunteer Respect', 'Transparency'],
    model_tier: 'haiku', default_budget: 5, tool_access: 'core',
    color: '#f97316', sprite_index: 5, mcp_servers: [],
  },
  {
    slug: 'operations', name: 'Operations & Systems', short_name: 'Operations',
    dept_index: 17,
    description: 'Process management, SOPs, workflow automation, vendor management, and organizational efficiency.',
    system_prompt: `You are an Operations Specialist. You build SOPs, workflow maps, meeting frameworks, vendor evaluations, and process automation plans. Maintain the knowledge base. Everything should be documented, measurable, and improvable.`,
    default_skills: ['SOP Building', 'Workflow Design', 'Process Automation', 'Vendor Management', 'Knowledge Base', 'QA Checklists'],
    rules: ['Document Everything', 'Automate ROI', 'Measure Efficiency', 'Continuous Improvement'],
    model_tier: 'sonnet', default_budget: 10, tool_access: 'core',
    color: '#6b7280', sprite_index: 2, mcp_servers: ['Supabase'],
  },
  {
    slug: 'seo', name: 'Marketing — SEO & Search', short_name: 'SEO',
    dept_index: 18,
    description: 'Search engine optimization, keyword research, technical SEO, link building, and site architecture.',
    system_prompt: `You are an SEO Specialist. You conduct SEO audits, keyword research, site architecture planning, schema markup implementation, and link building strategies. Optimize for Core Web Vitals, crawlability, and search intent matching.`,
    default_skills: ['Technical SEO', 'Keyword Research', 'Link Building', 'Schema Markup', 'Site Architecture', 'SEO Audits'],
    rules: ['Data-Driven', 'White-Hat Only', 'User Intent First', 'Measure Rankings'],
    model_tier: 'sonnet', default_budget: 10, tool_access: 'core',
    color: '#22d3ee', sprite_index: 4, mcp_servers: ['Tavily'],
  },
  {
    slug: 'sales', name: 'Sales', short_name: 'Sales',
    dept_index: 19,
    description: 'Customer personas, journey mapping, competitor analysis, sales funnels, and pricing strategy.',
    system_prompt: `You are a Sales Strategist. You create customer personas, map buyer journeys, analyze competitors, design sales funnels, and optimize pricing. Every recommendation needs data backing — market research, conversion data, or customer interviews.`,
    default_skills: ['Customer Personas', 'Journey Mapping', 'Competitor Analysis', 'Funnel Design', 'Pricing Strategy', 'Discovery Calls'],
    rules: ['Customer-First', 'Data-Driven Pricing', 'Measure Retention', 'Close the Loop'],
    model_tier: 'sonnet', default_budget: 10, tool_access: 'core',
    color: '#f97316', sprite_index: 3, mcp_servers: ['Tavily', 'Supabase'],
  },
  {
    slug: 'social-media', name: 'Marketing — Social Media', short_name: 'Social Media',
    dept_index: 20,
    description: 'Social media strategy, content calendars, community management, influencer marketing, and PR.',
    system_prompt: `You are a Social Media Specialist. You develop social media strategies, plan content calendars, manage communities, run influencer campaigns, and handle PR outreach. Optimize for engagement, reach, and brand awareness across all platforms.`,
    default_skills: ['Social Strategy', 'Content Calendars', 'Community Management', 'Influencer Campaigns', 'PR Outreach', 'Crisis Comms'],
    rules: ['Platform-Native Content', 'Engagement Focus', 'Brand Voice Consistency', 'Trend Awareness'],
    model_tier: 'haiku', default_budget: 8, tool_access: 'core',
    color: '#e879f9', sprite_index: 1, mcp_servers: ['Tavily'],
  },
  {
    slug: 'strategy', name: 'Strategy & PMO', short_name: 'Strategy',
    dept_index: 21,
    description: 'Project planning, strategic leadership, and cross-functional coordination.',
    system_prompt: `You are a Strategy & PMO Lead. You lead project planning, coordinate cross-functional teams, convert ideas into technical handoffs and business proposals. Think like a senior solutions architect — systems thinking, data contracts, and architectural decisions.`,
    default_skills: ['Project Planning', 'Strategic Coordination', 'Business Proposals', 'Technical Handoffs', 'Cross-Functional Leadership'],
    rules: ['Systems Thinking', 'Decision Logging', 'Stakeholder Alignment', 'Scope Discipline'],
    model_tier: 'opus', default_budget: 15, tool_access: 'standard',
    color: '#818cf8', sprite_index: 0, mcp_servers: ['Tavily', 'Context7'],
  },
];

// ── Skill Definitions (Layer 2 — 476 rows) ──────────────────────────────────

interface SkillSeed {
  dept_slug: string;
  slug: string;
  name: string;
  seniority: string;
  company_type: string;
  description: string;
  skills_path: string;
}

// All 476 skills grouped by department slug
const ALL_SKILLS: SkillSeed[] = [
  // ── Engineering & Technology (4) ──
  { dept_slug: 'engineering', slug: 'ai-content-policy', name: 'AI Content Policy Specialist', seniority: 'Senior', company_type: 'SaaS / Tech', description: 'Develops and enforces policies governing AI-generated content across the product.', skills_path: '.agents/skills/AI & Technology/ai-content-policy' },
  { dept_slug: 'engineering', slug: 'ai-ethics-policy', name: 'AI Ethics Officer', seniority: 'Senior', company_type: 'SaaS / Tech', description: 'Creates and maintains the AI ethics framework covering bias detection, fairness, and responsible deployment.', skills_path: '.agents/skills/AI & Technology/ai-ethics-policy' },
  { dept_slug: 'engineering', slug: 'ai-use-case-finder', name: 'AI Solutions Engineer', seniority: 'Mid-Level', company_type: 'SaaS / Tech', description: 'Identifies and evaluates viable AI/ML use cases, building proof-of-concepts and ROI models.', skills_path: '.agents/skills/AI & Technology/ai-use-case-finder' },
  { dept_slug: 'engineering', slug: 'automation-workflow', name: 'Automation Engineer', seniority: 'Mid-Level', company_type: 'SaaS / Tech', description: 'Designs and implements workflow automation systems integrating internal tools and third-party services.', skills_path: '.agents/skills/AI & Technology/automation-workflow' },

  // ── Marketing — Paid Acquisition (22) ──
  { dept_slug: 'marketing-paid', slug: 'ad-copy', name: 'Ad Copywriter', seniority: 'Mid-Level', company_type: 'SaaS / Any', description: 'Writes compelling ad copy for paid campaigns across platforms, optimizing for CTR and conversion.', skills_path: '.agents/skills/Ads & Paid Media/ad-copy' },
  { dept_slug: 'marketing-paid', slug: 'ad-creative-brief', name: 'Ad Creative Strategist', seniority: 'Mid-Level', company_type: 'SaaS / Any', description: 'Produces creative briefs for ad campaigns defining visual direction, messaging, and platform specs.', skills_path: '.agents/skills/Ads & Paid Media/ad-creative-brief' },
  { dept_slug: 'marketing-paid', slug: 'ad-performance-report', name: 'Paid Media Analyst', seniority: 'Senior', company_type: 'SaaS / Any', description: 'Builds ad performance reports analyzing ROAS, CPA, and attribution data for budget decisions.', skills_path: '.agents/skills/Ads & Paid Media/ad-performance-report' },
  { dept_slug: 'marketing-paid', slug: 'ad-spend-calculator', name: 'Media Budget Analyst', seniority: 'Senior', company_type: 'SaaS / Any', description: 'Models and forecasts ad spend across channels, calculating expected CAC and LTV ratios.', skills_path: '.agents/skills/Ads & Paid Media/ad-spend-calculator' },
  { dept_slug: 'marketing-paid', slug: 'affiliate-program', name: 'Affiliate Program Manager', seniority: 'Senior', company_type: 'SaaS / E-commerce', description: 'Designs and manages affiliate programs including commission structures and tracking systems.', skills_path: '.agents/skills/Ads & Paid Media/affiliate-program' },
  { dept_slug: 'marketing-paid', slug: 'affiliate-recruitment', name: 'Affiliate Recruiter', seniority: 'Mid-Level', company_type: 'SaaS / E-commerce', description: 'Sources, evaluates, and onboards affiliate partners and content creators.', skills_path: '.agents/skills/Ads & Paid Media/affiliate-recruitment' },
  { dept_slug: 'marketing-paid', slug: 'affiliate-terms', name: 'Affiliate Legal Coordinator', seniority: 'Senior', company_type: 'SaaS / E-commerce', description: 'Drafts and maintains affiliate terms and conditions with compliance requirements.', skills_path: '.agents/skills/Ads & Paid Media/affiliate-terms' },
  { dept_slug: 'marketing-paid', slug: 'bundle-creator', name: 'Product Bundling Specialist', seniority: 'Mid-Level', company_type: 'SaaS / E-commerce', description: 'Creates product bundles and package offers to increase average order value.', skills_path: '.agents/skills/Ads & Paid Media/bundle-creator' },
  { dept_slug: 'marketing-paid', slug: 'cross-sell-strategy', name: 'Cross-Sell Strategist', seniority: 'Mid-Level', company_type: 'SaaS / E-commerce', description: 'Develops cross-selling strategies across product lines with upsell paths.', skills_path: '.agents/skills/Ads & Paid Media/cross-sell-strategy' },
  { dept_slug: 'marketing-paid', slug: 'discount-strategy', name: 'Pricing & Promotions Specialist', seniority: 'Mid-Level', company_type: 'SaaS / E-commerce', description: 'Plans discount and promotional strategies balancing revenue with acquisition goals.', skills_path: '.agents/skills/Ads & Paid Media/discount-strategy' },
  { dept_slug: 'marketing-paid', slug: 'facebook-ad-campaign', name: 'Facebook Ads Manager', seniority: 'Mid-Level', company_type: 'SaaS / Any', description: 'Plans and optimizes Facebook/Meta ad campaigns including audience targeting and pixel configuration.', skills_path: '.agents/skills/Ads & Paid Media/facebook-ad-campaign' },
  { dept_slug: 'marketing-paid', slug: 'google-ads-campaign', name: 'Google Ads Specialist', seniority: 'Mid-Level', company_type: 'SaaS / Any', description: 'Manages Google Ads campaigns including keyword strategy and bid management.', skills_path: '.agents/skills/Ads & Paid Media/google-ads-campaign' },
  { dept_slug: 'marketing-paid', slug: 'high-ticket-sales-page', name: 'High-Ticket Sales Copywriter', seniority: 'Senior', company_type: 'SaaS / Any', description: 'Crafts long-form sales pages for high-ticket offers using persuasion frameworks.', skills_path: '.agents/skills/Ads & Paid Media/high-ticket-sales-page' },
  { dept_slug: 'marketing-paid', slug: 'linkedin-ad-campaign', name: 'LinkedIn Ads Specialist', seniority: 'Mid-Level', company_type: 'SaaS / B2B', description: 'Runs LinkedIn ad campaigns targeting B2B audiences with Sponsored Content and InMail.', skills_path: '.agents/skills/Ads & Paid Media/linkedin-ad-campaign' },
  { dept_slug: 'marketing-paid', slug: 'lookalike-audience-plan', name: 'Audience Targeting Strategist', seniority: 'Senior', company_type: 'SaaS / Any', description: 'Builds lookalike and custom audience strategies across ad platforms.', skills_path: '.agents/skills/Ads & Paid Media/lookalike-audience-plan' },
  { dept_slug: 'marketing-paid', slug: 'media-buy-plan', name: 'Media Buyer', seniority: 'Senior', company_type: 'SaaS / Any', description: 'Plans and executes media buys across digital and traditional channels.', skills_path: '.agents/skills/Ads & Paid Media/media-buy-plan' },
  { dept_slug: 'marketing-paid', slug: 'podcast-ad-script', name: 'Podcast Ad Scriptwriter', seniority: 'Mid-Level', company_type: 'SaaS / Any', description: 'Writes host-read and produced podcast ad scripts for brand awareness and direct response.', skills_path: '.agents/skills/Ads & Paid Media/podcast-ad-script' },
  { dept_slug: 'marketing-paid', slug: 'retargeting-strategy', name: 'Retargeting Specialist', seniority: 'Senior', company_type: 'SaaS / Any', description: 'Designs retargeting funnels across web, social, and email to reduce abandonment.', skills_path: '.agents/skills/Ads & Paid Media/retargeting-strategy' },
  { dept_slug: 'marketing-paid', slug: 'sales-page', name: 'Sales Page Copywriter', seniority: 'Mid-Level', company_type: 'SaaS / Any', description: 'Writes conversion-focused sales pages with clear value propositions and CTAs.', skills_path: '.agents/skills/Ads & Paid Media/sales-page' },
  { dept_slug: 'marketing-paid', slug: 'tiktok-ad-script', name: 'TikTok Ad Scriptwriter', seniority: 'Mid-Level', company_type: 'SaaS / Any', description: 'Creates short-form video ad scripts for TikTok campaigns.', skills_path: '.agents/skills/Ads & Paid Media/tiktok-ad-script' },
  { dept_slug: 'marketing-paid', slug: 'tripwire-offer', name: 'Tripwire Offer Designer', seniority: 'Mid-Level', company_type: 'SaaS / Any', description: 'Designs low-cost entry offers that convert leads into buyers.', skills_path: '.agents/skills/Ads & Paid Media/tripwire-offer' },
  { dept_slug: 'marketing-paid', slug: 'youtube-ad-script', name: 'YouTube Ad Scriptwriter', seniority: 'Mid-Level', company_type: 'SaaS / Any', description: 'Writes YouTube pre-roll and in-stream ad scripts with strong hooks.', skills_path: '.agents/skills/Ads & Paid Media/youtube-ad-script' },

  // ── Data & Analytics (23) ──
  { dept_slug: 'data-analytics', slug: 'ab-test-plan', name: 'A/B Test Lead', seniority: 'Senior', company_type: 'SaaS / Any', description: 'Designs A/B testing programs with hypotheses, sample sizes, and significance thresholds.', skills_path: '.agents/skills/Analytics & Data/ab-test-plan' },
  { dept_slug: 'data-analytics', slug: 'analytics-setup-guide', name: 'Analytics Implementation Engineer', seniority: 'Mid-Level', company_type: 'SaaS / Any', description: 'Sets up analytics infrastructure including event tracking and tag management.', skills_path: '.agents/skills/Analytics & Data/analytics-setup-guide' },
  { dept_slug: 'data-analytics', slug: 'attribution-model', name: 'Attribution Analyst', seniority: 'Senior', company_type: 'SaaS / Any', description: 'Builds multi-touch attribution models to assign conversion credit across channels.', skills_path: '.agents/skills/Analytics & Data/attribution-model' },
  { dept_slug: 'data-analytics', slug: 'benchmarking-report', name: 'Competitive Intelligence Analyst', seniority: 'Mid-Level', company_type: 'SaaS / Any', description: 'Produces benchmarking reports comparing metrics against industry standards.', skills_path: '.agents/skills/Analytics & Data/benchmarking-report' },
  { dept_slug: 'data-analytics', slug: 'cohort-analysis', name: 'Cohort Analyst', seniority: 'Senior', company_type: 'SaaS / Any', description: 'Tracks user behavior over time identifying retention patterns and revenue trends.', skills_path: '.agents/skills/Analytics & Data/cohort-analysis' },
  { dept_slug: 'data-analytics', slug: 'conversion-funnel-analysis', name: 'CRO Analyst', seniority: 'Senior', company_type: 'SaaS / Any', description: 'Analyzes conversion funnels identifying drop-off points and UX improvements.', skills_path: '.agents/skills/Analytics & Data/conversion-funnel-analysis' },
  { dept_slug: 'data-analytics', slug: 'customer-lifetime-value', name: 'CLV Analyst', seniority: 'Senior', company_type: 'SaaS / Any', description: 'Calculates and forecasts customer lifetime value using predictive models.', skills_path: '.agents/skills/Analytics & Data/customer-lifetime-value' },
  { dept_slug: 'data-analytics', slug: 'data-collection-plan', name: 'Data Collection Specialist', seniority: 'Mid-Level', company_type: 'SaaS / Any', description: 'Designs data collection plans ensuring completeness and privacy compliance.', skills_path: '.agents/skills/Analytics & Data/data-collection-plan' },
  { dept_slug: 'data-analytics', slug: 'data-dashboard-design', name: 'Dashboard Designer', seniority: 'Mid-Level', company_type: 'SaaS / Any', description: 'Designs data dashboards surfacing actionable insights for stakeholders.', skills_path: '.agents/skills/Analytics & Data/data-dashboard-design' },
  { dept_slug: 'data-analytics', slug: 'feedback-analysis', name: 'Feedback Analyst', seniority: 'Mid-Level', company_type: 'SaaS / Any', description: 'Aggregates and analyzes customer feedback to identify themes and priorities.', skills_path: '.agents/skills/Analytics & Data/feedback-analysis' },
  { dept_slug: 'data-analytics', slug: 'game-publishing-data-architect', name: 'Game Data Architect', seniority: 'Senior', company_type: 'Gaming / SaaS', description: 'Architects data pipelines for game publishing analytics.', skills_path: '.agents/skills/Analytics & Data/game-publishing-data-architect' },
  { dept_slug: 'data-analytics', slug: 'grant-report', name: 'Grant Reporting Analyst', seniority: 'Mid-Level', company_type: 'Nonprofit / Any', description: 'Prepares grant performance reports with financial and outcome data.', skills_path: '.agents/skills/Analytics & Data/grant-report' },
  { dept_slug: 'data-analytics', slug: 'impact-report', name: 'Impact Reporting Analyst', seniority: 'Mid-Level', company_type: 'Nonprofit / Any', description: 'Produces impact reports measuring outcomes against stated goals.', skills_path: '.agents/skills/Analytics & Data/impact-report' },
  { dept_slug: 'data-analytics', slug: 'kpi-dashboard', name: 'KPI Dashboard Developer', seniority: 'Mid-Level', company_type: 'SaaS / Any', description: 'Builds KPI dashboards tracking key business metrics in real-time.', skills_path: '.agents/skills/Analytics & Data/kpi-dashboard' },
  { dept_slug: 'data-analytics', slug: 'marketplace-fee-structure', name: 'Marketplace Pricing Analyst', seniority: 'Senior', company_type: 'Marketplace / SaaS', description: 'Designs marketplace fee structures balancing revenue with seller economics.', skills_path: '.agents/skills/Analytics & Data/marketplace-fee-structure' },
  { dept_slug: 'data-analytics', slug: 'marketplace-metrics', name: 'Marketplace Analytics Lead', seniority: 'Senior', company_type: 'Marketplace / SaaS', description: 'Defines and tracks marketplace-specific metrics like GMV and liquidity.', skills_path: '.agents/skills/Analytics & Data/marketplace-metrics' },
  { dept_slug: 'data-analytics', slug: 'metric-definition-guide', name: 'Metrics Definition Analyst', seniority: 'Mid-Level', company_type: 'SaaS / Any', description: 'Creates metric definition guides ensuring consistent measurement across teams.', skills_path: '.agents/skills/Analytics & Data/metric-definition-guide' },
  { dept_slug: 'data-analytics', slug: 'nonprofit-board-packet', name: 'Board Reporting Analyst', seniority: 'Mid-Level', company_type: 'Nonprofit', description: 'Assembles board packets with financial summaries and program updates.', skills_path: '.agents/skills/Analytics & Data/nonprofit-board-packet' },
  { dept_slug: 'data-analytics', slug: 'prompt-library', name: 'Prompt Engineer', seniority: 'Mid-Level', company_type: 'SaaS / Any', description: 'Builds and maintains a prompt library for AI-powered features.', skills_path: '.agents/skills/Analytics & Data/prompt-library' },
  { dept_slug: 'data-analytics', slug: 'saas-metrics-dashboard', name: 'SaaS Metrics Analyst', seniority: 'Senior', company_type: 'SaaS', description: 'Builds SaaS dashboards tracking MRR, ARR, churn, and NDR.', skills_path: '.agents/skills/Analytics & Data/saas-metrics-dashboard' },
  { dept_slug: 'data-analytics', slug: 'sentiment-analysis', name: 'Sentiment Analyst', seniority: 'Mid-Level', company_type: 'SaaS / Any', description: 'Runs sentiment analysis on customer communications and social mentions.', skills_path: '.agents/skills/Analytics & Data/sentiment-analysis' },
  { dept_slug: 'data-analytics', slug: 'social-impact-measurement', name: 'Social Impact Analyst', seniority: 'Mid-Level', company_type: 'Nonprofit / Any', description: 'Designs frameworks to quantify social impact outcomes.', skills_path: '.agents/skills/Analytics & Data/social-impact-measurement' },
  { dept_slug: 'data-analytics', slug: 'survey-analysis', name: 'Survey Data Analyst', seniority: 'Mid-Level', company_type: 'SaaS / Any', description: 'Analyzes survey data producing statistical summaries and insight reports.', skills_path: '.agents/skills/Analytics & Data/survey-analysis' },

  // ── Brand & Design (24) ──
  ...buildSkillsFromList('brand-design', '.agents/skills/Branding & Design', [
    ['brand-architecture', 'Brand Architect', 'Senior', 'SaaS / Any', 'Defines brand architecture across product lines and sub-brands.'],
    ['brand-audit', 'Brand Auditor', 'Senior', 'SaaS / Any', 'Conducts brand audits assessing consistency, perception, and competitive positioning.'],
    ['brand-identity-guide', 'Brand Identity Designer', 'Senior', 'SaaS / Any', 'Creates brand identity guides covering logo, typography, imagery, and iconography.'],
    ['brand-positioning-statement', 'Brand Positioning Strategist', 'Senior', 'SaaS / Any', 'Crafts brand positioning statements defining target, differentiator, and reason to believe.'],
    ['brand-refresh', 'Brand Refresh Lead', 'Senior', 'SaaS / Any', 'Leads brand refresh initiatives including research, creative development, and rollout.'],
    ['brand-tagline', 'Tagline & Messaging Writer', 'Mid-Level', 'SaaS / Any', 'Develops brand taglines, slogans, and key messaging frameworks.'],
    ['brand-voice-guide', 'Brand Voice Strategist', 'Senior', 'SaaS / Any', 'Defines brand voice and tone guidelines with channel-specific adaptations.'],
    ['color-palette-generator', 'Color Systems Designer', 'Mid-Level', 'SaaS / Any', 'Creates color palettes aligned with brand psychology and accessibility.'],
    ['executive-resume', 'Executive Resume Writer', 'Mid-Level', 'Any', 'Writes executive-level resumes highlighting leadership impact.'],
    ['expert-positioning', 'Expert Positioning Consultant', 'Senior', 'Consulting / Any', 'Positions individuals as thought leaders through messaging and visibility planning.'],
    ['icon-set-brief', 'Icon Designer', 'Mid-Level', 'SaaS / Any', 'Creates icon set design briefs specifying style, grid system, and use cases.'],
    ['merch-design-brief', 'Merchandise Designer', 'Mid-Level', 'E-commerce / Any', 'Produces merchandise design briefs for branded swag and apparel.'],
    ['mission-statement', 'Mission Statement Writer', 'Senior', 'Any', 'Crafts mission, vision, and values statements aligned with stakeholder expectations.'],
    ['naming-workshop', 'Naming Strategist', 'Senior', 'SaaS / Any', 'Facilitates naming workshops with linguistic screening and trademark checks.'],
    ['packaging-brief', 'Packaging Designer', 'Mid-Level', 'E-commerce / CPG', 'Creates packaging design briefs covering materials, dimensions, and print specs.'],
    ['portfolio-page', 'Portfolio Designer', 'Mid-Level', 'Any', 'Designs portfolio pages showcasing work, metrics, and client outcomes.'],
    ['presentation-template-guide', 'Presentation Designer', 'Mid-Level', 'SaaS / Any', 'Builds presentation template systems for consistent company-wide decks.'],
    ['rebrand-plan', 'Rebrand Project Manager', 'Senior', 'SaaS / Any', 'Plans and executes full rebrands including timeline and asset migration.'],
    ['signage-brief', 'Environmental Designer', 'Mid-Level', 'Retail / Any', 'Creates signage and environmental design briefs for physical spaces.'],
    ['signature-talk', 'Signature Talk Developer', 'Senior', 'Consulting / Any', 'Develops keynote presentations that establish thought leadership.'],
    ['speaking-one-sheet', 'Speaker Marketing Specialist', 'Mid-Level', 'Consulting / Any', 'Creates speaker one-sheets and promotional materials.'],
    ['style-tile', 'Style Tile Designer', 'Mid-Level', 'SaaS / Any', 'Produces style tiles as visual design references and mood boards.'],
    ['unboxing-experience', 'Unboxing Experience Designer', 'Mid-Level', 'E-commerce / DTC', 'Designs memorable unboxing experiences including packaging and inserts.'],
    ['visual-identity-brief', 'Visual Identity Director', 'Senior', 'SaaS / Any', 'Creates comprehensive visual identity briefs guiding the full design system.'],
  ]),

  // ── Consulting (18) ──
  ...buildSkillsFromList('consulting', '.agents/skills/Client & Consulting', [
    ['agency-onboarding', 'Agency Onboarding Specialist', 'Mid-Level', 'SaaS / Agency', 'Designs and manages new client onboarding processes.'],
    ['client-feedback-system', 'Client Feedback Coordinator', 'Mid-Level', 'SaaS / Agency', 'Builds systems for collecting and acting on client feedback.'],
    ['client-intake-form', 'Client Intake Specialist', 'Junior', 'SaaS / Agency', 'Designs client intake forms and qualification workflows.'],
    ['client-report-template', 'Client Reporting Specialist', 'Mid-Level', 'SaaS / Agency', 'Creates client-facing report templates communicating results.'],
    ['client-transformation-story', 'Case Study Writer', 'Mid-Level', 'SaaS / Agency', 'Writes client success narratives for sales enablement.'],
    ['cohort-program', 'Cohort Program Director', 'Senior', 'SaaS / Education', 'Designs cohort-based programs with peer learning and progression.'],
    ['consulting-framework', 'Framework Developer', 'Senior', 'Consulting', 'Builds proprietary consulting frameworks and methodologies.'],
    ['consulting-proposal-template', 'Proposal Writer', 'Mid-Level', 'Consulting / Agency', 'Writes consulting proposals covering scope, methodology, and pricing.'],
    ['diagnostic-assessment', 'Diagnostic Lead', 'Senior', 'Consulting', 'Conducts diagnostic assessments with gap analysis and recommendations.'],
    ['group-program-design', 'Group Program Designer', 'Senior', 'SaaS / Education', 'Designs group coaching programs with scalable delivery.'],
    ['industry-association-plan', 'Association Strategist', 'Senior', 'Any', 'Develops strategies for industry association engagement.'],
    ['mastermind-group', 'Mastermind Facilitator', 'Senior', 'Consulting / Education', 'Designs mastermind groups with structured sessions and accountability.'],
    ['project-scope-change', 'Change Order Manager', 'Mid-Level', 'SaaS / Agency', 'Manages scope change processes and contract amendments.'],
    ['quiz-generator', 'Quiz Builder', 'Mid-Level', 'SaaS / Any', 'Creates interactive quizzes for lead generation or evaluation.'],
    ['service-guarantee', 'Service Guarantee Designer', 'Senior', 'SaaS / Agency', 'Designs service guarantees and SLA commitments.'],
    ['service-productization', 'Productized Service Designer', 'Senior', 'Consulting / Agency', 'Transforms custom services into productized offerings.'],
    ['skill-assessment', 'Skill Assessment Designer', 'Mid-Level', 'SaaS / Any', 'Builds skill assessment tools and competency matrices.'],
    ['survey-builder', 'Survey Builder', 'Mid-Level', 'SaaS / Any', 'Designs surveys with proper question design and branching logic.'],
  ]),

  // ── Content (51) ──
  ...buildSkillsFromList('content', '.agents/skills/Content & Copywriting', [
    ['about-page', 'About Page Copywriter', 'Mid-Level', 'SaaS / Any', 'Writes compelling about pages conveying company story and trust signals.'],
    ['article-rewriter', 'Content Rewriter', 'Junior', 'SaaS / Any', 'Rewrites and refreshes existing content for SEO and readability.'],
    ['authority-content-strategy', 'Authority Content Strategist', 'Senior', 'SaaS / Any', 'Develops content strategies establishing thought leadership.'],
    ['blog-post', 'Blog Writer', 'Mid-Level', 'SaaS / Any', 'Writes SEO-optimized blog posts driving organic traffic.'],
    ['book-outline', 'Book Outline Strategist', 'Senior', 'Any', 'Creates detailed book outlines with chapter structures.'],
    ['book-proposal', 'Book Proposal Writer', 'Senior', 'Any', 'Writes book proposals for publishers.'],
    ['brand-story', 'Brand Storyteller', 'Senior', 'SaaS / Any', 'Crafts origin stories and brand narratives.'],
    ['caption-writer', 'Social Caption Writer', 'Junior', 'SaaS / Any', 'Writes engaging social media captions per platform.'],
    ['case-study', 'Case Study Writer', 'Mid-Level', 'SaaS / Any', 'Produces case studies with problem-solution-results framework.'],
    ['collection-page-copy', 'Collection Page Copywriter', 'Mid-Level', 'E-commerce', 'Writes SEO-rich category page copy.'],
    ['comparison-article', 'Comparison Article Writer', 'Mid-Level', 'SaaS / Any', 'Writes comparison articles positioned for bottom-of-funnel SEO.'],
    ['content-audit', 'Content Auditor', 'Senior', 'SaaS / Any', 'Conducts content audits assessing performance and identifying gaps.'],
    ['content-brief', 'Content Brief Writer', 'Mid-Level', 'SaaS / Any', 'Creates detailed content briefs for writers.'],
    ['content-calendar', 'Content Calendar Manager', 'Mid-Level', 'SaaS / Any', 'Plans editorial calendars across channels.'],
    ['content-cluster-plan', 'Content Cluster Strategist', 'Senior', 'SaaS / Any', 'Builds topic cluster strategies for topical authority.'],
    ['content-gap-finder', 'Content Gap Analyst', 'Mid-Level', 'SaaS / Any', 'Identifies content gaps by analyzing competitor content.'],
    ['content-pillar-strategy', 'Content Pillar Strategist', 'Senior', 'SaaS / Any', 'Designs content pillar strategies organizing brand expertise.'],
    ['content-repurpose', 'Content Repurposing Specialist', 'Mid-Level', 'SaaS / Any', 'Transforms content into multiple formats for max reach.'],
    ['content-style-guide', 'Content Style Guide Owner', 'Senior', 'SaaS / Any', 'Creates and maintains content style guides.'],
    ['donation-page-copy', 'Donation Page Copywriter', 'Mid-Level', 'Nonprofit', 'Writes persuasive donation page copy.'],
    ['ebook-outline', 'Ebook Writer', 'Mid-Level', 'SaaS / Any', 'Outlines and writes ebooks as lead magnets.'],
    ['expert-roundup-pitch', 'Expert Roundup Coordinator', 'Mid-Level', 'SaaS / Any', 'Pitches and coordinates expert roundup articles.'],
    ['faq-generator', 'FAQ Writer', 'Mid-Level', 'SaaS / Any', 'Creates comprehensive FAQ sections.'],
    ['feature-announcement', 'Feature Announcement Writer', 'Mid-Level', 'SaaS', 'Writes feature announcements and product updates.'],
    ['ghostwriter-brief', 'Ghostwriter', 'Mid-Level', 'SaaS / Any', 'Produces ghostwritten content for executives.'],
    ['headline-generator', 'Headline Writer', 'Mid-Level', 'SaaS / Any', 'Crafts high-converting headlines.'],
    ['help-center-article', 'Help Center Writer', 'Mid-Level', 'SaaS', 'Writes clear help center articles.'],
    ['hook-generator', 'Hook Writer', 'Mid-Level', 'SaaS / Any', 'Writes attention-grabbing hooks for content and ads.'],
    ['landing-page-copy', 'Landing Page Copywriter', 'Mid-Level', 'SaaS / Any', 'Writes landing page copy optimized for conversion.'],
    ['linkedin-article', 'LinkedIn Article Writer', 'Mid-Level', 'SaaS / B2B', 'Writes long-form LinkedIn articles.'],
    ['listicle-generator', 'Listicle Writer', 'Junior', 'SaaS / Any', 'Produces scannable listicle-format content.'],
    ['microcopy-writer', 'UX Microcopy Writer', 'Mid-Level', 'SaaS / Any', 'Writes UI microcopy including button labels and error messages.'],
    ['newsletter-builder', 'Newsletter Writer', 'Mid-Level', 'SaaS / Any', 'Creates newsletter editions with curated content.'],
    ['newsletter-strategy', 'Newsletter Strategist', 'Senior', 'SaaS / Any', 'Develops newsletter strategy including growth and monetization.'],
    ['pillar-page', 'Pillar Page Author', 'Senior', 'SaaS / Any', 'Writes comprehensive pillar pages as authoritative resources.'],
    ['podcast-one-sheet', 'Podcast One-Sheet Creator', 'Mid-Level', 'Any', 'Creates podcast pitch one-sheets.'],
    ['podcast-show-notes', 'Podcast Show Notes Writer', 'Mid-Level', 'Any', 'Writes podcast show notes with timestamps and takeaways.'],
    ['press-kit', 'Press Kit Assembler', 'Mid-Level', 'SaaS / Any', 'Assembles press kits with brand assets and key stats.'],
    ['press-release', 'Press Release Writer', 'Mid-Level', 'SaaS / Any', 'Writes press releases for launches and milestones.'],
    ['pricing-page-copy', 'Pricing Page Copywriter', 'Mid-Level', 'SaaS', 'Writes pricing page copy that drives plan selection.'],
    ['product-changelog', 'Product Changelog Writer', 'Mid-Level', 'SaaS', 'Maintains the product changelog.'],
    ['product-description', 'Product Description Writer', 'Mid-Level', 'E-commerce / SaaS', 'Writes product descriptions highlighting benefits.'],
    ['product-faq', 'Product FAQ Writer', 'Mid-Level', 'SaaS / E-commerce', 'Creates product-specific FAQs.'],
    ['professional-bio', 'Bio Writer', 'Mid-Level', 'Any', 'Writes professional bios for team pages and profiles.'],
    ['recipe-card', 'Recipe Content Creator', 'Junior', 'Food / Lifestyle', 'Creates recipe cards with structured data.'],
    ['release-notes', 'Release Notes Writer', 'Mid-Level', 'SaaS', 'Writes release notes communicating product updates.'],
    ['script-to-blog', 'Content Transformer', 'Mid-Level', 'Any', 'Converts video/audio scripts into written blog content.'],
    ['seo-content-brief', 'SEO Content Writer', 'Mid-Level', 'SaaS / Any', 'Creates SEO-focused content briefs.'],
    ['speech-writer', 'Speechwriter', 'Senior', 'Any', 'Writes speeches for executives.'],
    ['thought-leader-content-plan', 'Thought Leadership Planner', 'Senior', 'SaaS / Any', 'Plans thought leadership content programs.'],
    ['thought-leadership', 'Thought Leadership Writer', 'Senior', 'SaaS / Any', 'Produces thought leadership articles and whitepapers.'],
  ]),

  // ── Education (20) ──
  ...buildSkillsFromList('education', '.agents/skills/Courses & Education', [
    ['certification-program', 'Certification Program Designer', 'Senior', 'SaaS / Education', 'Designs certification programs with competency frameworks.'],
    ['class-schedule-planner', 'Schedule Planner', 'Mid-Level', 'Education', 'Plans class and session schedules.'],
    ['continuing-education', 'Continuing Education Coordinator', 'Mid-Level', 'Any', 'Develops continuing education programs.'],
    ['course-outline', 'Course Designer', 'Senior', 'SaaS / Education', 'Designs course outlines with learning objectives.'],
    ['curriculum-review', 'Curriculum Reviewer', 'Senior', 'Education', 'Evaluates curriculum alignment with standards.'],
    ['fitness-program-outline', 'Fitness Program Designer', 'Mid-Level', 'Health / Fitness', 'Creates structured fitness programs.'],
    ['homework-assignment', 'Assignment Designer', 'Junior', 'Education', 'Creates homework and practice exercises.'],
    ['learning-path', 'Learning Path Architect', 'Senior', 'SaaS / Education', 'Designs beginner-to-advanced learning paths.'],
    ['lesson-plan', 'Lesson Plan Developer', 'Mid-Level', 'Education / Any', 'Develops detailed lesson plans.'],
    ['micro-course', 'Micro-Course Creator', 'Mid-Level', 'SaaS / Education', 'Creates bite-sized learning modules.'],
    ['nutrition-content-plan', 'Nutrition Content Specialist', 'Mid-Level', 'Health / Wellness', 'Plans nutrition-focused content.'],
    ['podcast-launch', 'Podcast Launch Manager', 'Mid-Level', 'Any', 'Plans and executes podcast launches.'],
    ['student-feedback-form', 'Student Feedback Analyst', 'Mid-Level', 'Education / SaaS', 'Designs and analyzes student feedback forms.'],
    ['study-guide', 'Study Guide Creator', 'Mid-Level', 'Education', 'Creates study guides reinforcing key concepts.'],
    ['ted-talk-outline', 'TED-Style Talk Coach', 'Senior', 'Any', 'Develops TED-style talk outlines.'],
    ['webinar-planner', 'Webinar Producer', 'Mid-Level', 'SaaS / Any', 'Plans and produces webinars.'],
    ['wellness-assessment', 'Wellness Assessment Designer', 'Mid-Level', 'Health / Wellness', 'Creates wellness assessments.'],
    ['wellness-workshop-plan', 'Wellness Workshop Designer', 'Mid-Level', 'Health / Wellness', 'Designs wellness workshop programs.'],
    ['workshop-builder', 'Workshop Designer', 'Senior', 'SaaS / Education', 'Designs interactive workshops.'],
    ['workshop-handout', 'Workshop Materials Creator', 'Mid-Level', 'Education', 'Creates workshop handouts and workbooks.'],
  ]),

  // ── E-commerce (24) ──
  ...buildSkillsFromList('ecommerce', '.agents/skills/E-commerce & Products', [
    ['cross-border-selling', 'International Commerce Manager', 'Senior', 'E-commerce', 'Manages cross-border selling operations.'],
    ['dropshipping-supplier-brief', 'Dropshipping Specialist', 'Mid-Level', 'E-commerce', 'Manages supplier relationships for dropshipping.'],
    ['exchange-policy', 'Returns Policy Manager', 'Mid-Level', 'E-commerce / Retail', 'Designs exchange and return policies.'],
    ['food-delivery-strategy', 'Food Delivery Strategist', 'Senior', 'Food / Delivery', 'Develops food delivery strategies.'],
    ['food-truck-business-plan', 'Food Truck Planner', 'Senior', 'Food / Restaurant', 'Creates food truck business plans.'],
    ['gift-guide', 'Gift Guide Curator', 'Mid-Level', 'E-commerce / Retail', 'Curates seasonal gift guides.'],
    ['investment-property-analysis', 'Investment Property Analyst', 'Senior', 'Real Estate / Finance', 'Analyzes investment properties.'],
    ['lease-agreement-checklist', 'Lease Agreement Specialist', 'Mid-Level', 'Real Estate', 'Manages lease agreement checklists.'],
    ['marketplace-listing', 'Marketplace Listing Specialist', 'Mid-Level', 'Marketplace', 'Creates and optimizes marketplace listings.'],
    ['neighborhood-guide', 'Neighborhood Content Creator', 'Mid-Level', 'Real Estate', 'Writes neighborhood guides.'],
    ['open-house-plan', 'Open House Coordinator', 'Mid-Level', 'Real Estate', 'Plans and executes open house events.'],
    ['product-recall-plan', 'Product Recall Coordinator', 'Senior', 'E-commerce / CPG', 'Develops product recall plans.'],
    ['product-sourcing-brief', 'Product Sourcing Specialist', 'Mid-Level', 'E-commerce', 'Creates product sourcing briefs.'],
    ['property-listing', 'Property Listing Writer', 'Mid-Level', 'Real Estate', 'Writes compelling property listings.'],
    ['property-management-sop', 'Property Management SOP Manager', 'Senior', 'Real Estate', 'Develops property management SOPs.'],
    ['real-estate-crm-setup', 'Real Estate CRM Admin', 'Mid-Level', 'Real Estate', 'Sets up CRM systems for real estate.'],
    ['real-estate-newsletter', 'Real Estate Newsletter Writer', 'Mid-Level', 'Real Estate', 'Creates real estate newsletters.'],
    ['rental-listing', 'Rental Listing Specialist', 'Mid-Level', 'Real Estate', 'Writes rental property listings.'],
    ['seasonal-inventory-plan', 'Seasonal Inventory Planner', 'Mid-Level', 'E-commerce / Retail', 'Plans seasonal inventory levels.'],
    ['seller-onboarding', 'Seller Onboarding Specialist', 'Mid-Level', 'Marketplace', 'Designs seller onboarding programs.'],
    ['size-guide', 'Size Guide Creator', 'Junior', 'E-commerce / Retail', 'Creates size guides to reduce returns.'],
    ['store-launch-plan', 'Store Launch Manager', 'Senior', 'E-commerce', 'Plans and executes online store launches.'],
    ['subscription-box-plan', 'Subscription Box Planner', 'Senior', 'E-commerce / DTC', 'Designs subscription box programs.'],
    ['wholesale-catalog', 'Wholesale Catalog Manager', 'Mid-Level', 'E-commerce / Wholesale', 'Creates wholesale catalogs.'],
  ]),

  // ── Email & CRM (42) ──
  ...buildSkillsFromList('email-crm', '.agents/skills/Email Marketing & Automation', [
    ['abandoned-cart-email', 'Cart Recovery Specialist', 'Mid-Level', 'E-commerce / SaaS', 'Creates abandoned cart email sequences.'],
    ['ambassador-program', 'Ambassador Program Manager', 'Mid-Level', 'SaaS / Any', 'Builds brand ambassador programs.'],
    ['black-friday-emails', 'Black Friday Campaign Manager', 'Mid-Level', 'E-commerce / SaaS', 'Plans Black Friday/Cyber Monday email campaigns.'],
    ['cart-recovery-sms', 'SMS Marketing Specialist', 'Mid-Level', 'E-commerce', 'Creates SMS cart recovery campaigns.'],
    ['cause-marketing-campaign', 'Cause Marketing Manager', 'Mid-Level', 'Any', 'Develops cause marketing campaigns.'],
    ['cold-outreach', 'Cold Outreach Specialist', 'Mid-Level', 'SaaS / B2B', 'Designs cold email outreach sequences.'],
    ['customer-review-strategy', 'Review Strategist', 'Mid-Level', 'SaaS / Any', 'Builds systems for collecting and leveraging reviews.'],
    ['downsell-sequence', 'Downsell Sequence Designer', 'Mid-Level', 'SaaS / E-commerce', 'Creates downsell email sequences.'],
    ['drip-campaign', 'Drip Campaign Designer', 'Mid-Level', 'SaaS / Any', 'Designs automated drip campaigns.'],
    ['email-ab-test-plan', 'Email A/B Test Strategist', 'Senior', 'SaaS / Any', 'Plans email A/B tests on subject lines and content.'],
    ['email-deliverability-audit', 'Deliverability Specialist', 'Senior', 'SaaS / Any', 'Audits email deliverability and sender reputation.'],
    ['email-design-system', 'Email Design System Owner', 'Mid-Level', 'SaaS / Any', 'Builds modular email design systems.'],
    ['email-list-cleanup', 'List Hygiene Specialist', 'Mid-Level', 'SaaS / Any', 'Manages email list cleanup and health.'],
    ['email-newsletter-template', 'Email Template Designer', 'Mid-Level', 'SaaS / Any', 'Creates responsive email newsletter templates.'],
    ['email-preference-center', 'Preference Center Manager', 'Mid-Level', 'SaaS / Any', 'Designs email preference centers.'],
    ['email-sequence', 'Email Automation Architect', 'Senior', 'SaaS / Any', 'Architects complex email sequences with branching logic.'],
    ['email-subject-line-tester', 'Subject Line Specialist', 'Mid-Level', 'SaaS / Any', 'Tests and optimizes email subject lines.'],
    ['engagement-playbook', 'Engagement Playbook Owner', 'Senior', 'SaaS / Any', 'Creates engagement playbooks for each lifecycle stage.'],
    ['flash-sale-campaign', 'Flash Sale Manager', 'Mid-Level', 'E-commerce / SaaS', 'Plans flash sale campaigns.'],
    ['launch-email-sequence', 'Launch Email Designer', 'Senior', 'SaaS / Any', 'Designs product launch email sequences.'],
    ['loyalty-program', 'Loyalty Program Manager', 'Senior', 'SaaS / E-commerce', 'Designs and manages loyalty programs.'],
    ['milestone-email', 'Milestone Email Designer', 'Mid-Level', 'SaaS / Any', 'Creates milestone-triggered emails.'],
    ['order-bump-copy', 'Order Bump Copywriter', 'Mid-Level', 'E-commerce / SaaS', 'Writes order bump offers.'],
    ['payment-plan-offer', 'Payment Plan Specialist', 'Mid-Level', 'SaaS / Any', 'Designs payment plan offers.'],
    ['price-increase-notice', 'Price Change Comms Manager', 'Mid-Level', 'SaaS / Any', 'Writes price increase communications.'],
    ['product-launch-email', 'Product Launch Email Writer', 'Mid-Level', 'SaaS / Any', 'Writes product launch emails.'],
    ['re-engagement-email', 'Re-engagement Specialist', 'Mid-Level', 'SaaS / Any', 'Creates re-engagement email campaigns.'],
    ['referral-program', 'Referral Program Designer', 'Mid-Level', 'SaaS / Any', 'Designs referral programs.'],
    ['renewal-campaign', 'Renewal Campaign Manager', 'Mid-Level', 'SaaS', 'Creates subscription renewal campaigns.'],
    ['seasonal-campaign', 'Seasonal Campaign Manager', 'Mid-Level', 'E-commerce / Retail', 'Plans seasonal email campaigns.'],
    ['social-proof-collector', 'Social Proof Collector', 'Mid-Level', 'SaaS / Any', 'Systematically collects social proof.'],
    ['testimonial-collector', 'Testimonial Collector', 'Mid-Level', 'SaaS / Any', 'Builds testimonial collection workflows.'],
    ['thank-you-campaign', 'Thank-You Campaign Designer', 'Mid-Level', 'SaaS / Any', 'Creates post-purchase thank-you campaigns.'],
    ['transactional-email', 'Transactional Email Designer', 'Mid-Level', 'SaaS / E-commerce', 'Designs transactional emails.'],
    ['trial-to-paid-email', 'Trial Conversion Specialist', 'Mid-Level', 'SaaS', 'Designs trial-to-paid email sequences.'],
    ['two-sided-email-strategy', 'Two-Sided Email Strategist', 'Mid-Level', 'Marketplace / SaaS', 'Creates email strategies for two-sided marketplaces.'],
    ['upsell-sequence', 'Upsell Sequence Designer', 'Mid-Level', 'SaaS / E-commerce', 'Builds upsell email sequences.'],
    ['user-generated-content', 'UGC Campaign Manager', 'Mid-Level', 'SaaS / Any', 'Manages user-generated content campaigns.'],
    ['waitlist-builder', 'Waitlist Manager', 'Mid-Level', 'SaaS / Any', 'Builds product waitlists with engagement sequences.'],
    ['webinar-email-sequence', 'Webinar Email Designer', 'Mid-Level', 'SaaS / Any', 'Creates webinar email sequences.'],
    ['welcome-sequence', 'Welcome Sequence Designer', 'Mid-Level', 'SaaS / Any', 'Designs welcome email sequences.'],
    ['win-back-campaign', 'Win-Back Specialist', 'Mid-Level', 'SaaS / Any', 'Creates win-back campaigns for churned customers.'],
  ]),

  // ── Events (24) ──
  ...buildSkillsFromList('events', '.agents/skills/Events & Speaking', [
    ['award-application', 'Award Application Writer', 'Mid-Level', 'Any', 'Writes industry award applications.'],
    ['beta-launch-plan', 'Beta Launch Manager', 'Senior', 'SaaS / Any', 'Plans beta launches with feedback collection.'],
    ['catering-proposal', 'Catering Proposal Writer', 'Mid-Level', 'Events / Hospitality', 'Creates catering proposals.'],
    ['conference-planner', 'Conference Planner', 'Senior', 'Any', 'Plans conferences end-to-end.'],
    ['digital-product-plan', 'Digital Product Manager', 'Senior', 'SaaS / Any', 'Plans digital product development.'],
    ['event-budget-planner', 'Event Budget Planner', 'Mid-Level', 'Any', 'Creates event budgets.'],
    ['event-follow-up', 'Event Follow-Up Coordinator', 'Mid-Level', 'Any', 'Designs post-event follow-up sequences.'],
    ['event-marketing-plan', 'Event Marketing Manager', 'Mid-Level', 'Any', 'Develops event marketing plans.'],
    ['event-planner', 'Event Director', 'Senior', 'Any', 'Manages full event lifecycle.'],
    ['event-registration-page', 'Event Registration Designer', 'Mid-Level', 'Any', 'Designs event registration pages.'],
    ['event-run-of-show', 'Run-of-Show Coordinator', 'Mid-Level', 'Any', 'Creates detailed run-of-show documents.'],
    ['event-sponsorship-proposal', 'Sponsorship Manager', 'Senior', 'Any', 'Writes event sponsorship proposals.'],
    ['hybrid-event-plan', 'Hybrid Event Producer', 'Senior', 'Any', 'Plans hybrid in-person and virtual events.'],
    ['launch-assets', 'Launch Asset Coordinator', 'Mid-Level', 'SaaS / Any', 'Coordinates launch asset production.'],
    ['launch-checklist', 'Launch Manager', 'Senior', 'SaaS / Any', 'Manages product launch checklists.'],
    ['marketplace-launch-plan', 'Marketplace Launch Manager', 'Senior', 'Marketplace', 'Plans marketplace launches.'],
    ['networking-event-plan', 'Networking Event Planner', 'Mid-Level', 'Any', 'Plans networking events.'],
    ['product-hunt-launch', 'Product Hunt Strategist', 'Senior', 'SaaS', 'Plans Product Hunt launches.'],
    ['product-launch-plan', 'Product Launch Director', 'Senior', 'SaaS / Any', 'Directs product launches across teams.'],
    ['retreat-planner', 'Retreat Planner', 'Mid-Level', 'Any', 'Plans team retreats.'],
    ['speaker-outreach', 'Speaker Outreach Coordinator', 'Mid-Level', 'Any', 'Sources and recruits speakers.'],
    ['speaking-proposal', 'Speaking Proposal Writer', 'Mid-Level', 'Any', 'Writes speaking proposals.'],
    ['sponsor-thank-you', 'Sponsor Relations Coordinator', 'Mid-Level', 'Any', 'Manages post-event sponsor relations.'],
    ['virtual-event-platform', 'Virtual Event Producer', 'Senior', 'Any', 'Produces virtual events.'],
  ]),

  // ── Finance (28) ──
  ...buildSkillsFromList('finance', '.agents/skills/Finance & Pricing', [
    ['bookkeeping-setup', 'Bookkeeper', 'Junior', 'SaaS / Any', 'Sets up bookkeeping systems.'],
    ['breakeven-analysis', 'Breakeven Analyst', 'Mid-Level', 'SaaS / Any', 'Performs breakeven analysis.'],
    ['budget-planner', 'Budget Planner', 'Mid-Level', 'SaaS / Any', 'Creates departmental budgets.'],
    ['cash-flow-forecast', 'Cash Flow Analyst', 'Senior', 'SaaS / Any', 'Forecasts cash flow positions.'],
    ['commission-structure', 'Commission Designer', 'Mid-Level', 'SaaS / Any', 'Designs sales commission structures.'],
    ['compensation-plan', 'Compensation Analyst', 'Senior', 'SaaS / Any', 'Develops compensation plans.'],
    ['cost-analysis', 'Cost Analyst', 'Mid-Level', 'SaaS / Any', 'Performs cost analysis.'],
    ['expense-tracker', 'Expense Tracker Admin', 'Junior', 'SaaS / Any', 'Sets up expense tracking systems.'],
    ['financial-dashboard', 'Financial Dashboard Builder', 'Senior', 'SaaS / Any', 'Builds executive financial dashboards.'],
    ['financial-model', 'Financial Modeler', 'Senior', 'SaaS / Any', 'Builds financial models for fundraising.'],
    ['financial-projection', 'Financial Projection Analyst', 'Senior', 'SaaS / Any', 'Creates financial projections.'],
    ['freelance-rate-card', 'Freelance Rate Consultant', 'Mid-Level', 'Freelance / Agency', 'Develops freelance rate cards.'],
    ['fundraising-tracker', 'Fundraising Tracker', 'Mid-Level', 'Nonprofit / Startup', 'Tracks fundraising progress.'],
    ['grant-application', 'Grant Writer', 'Mid-Level', 'Nonprofit', 'Writes grant applications.'],
    ['investor-update', 'Investor Relations Analyst', 'Senior', 'SaaS / Startup', 'Writes investor update communications.'],
    ['invoice-template', 'Invoice Administrator', 'Junior', 'Any', 'Creates invoice templates.'],
    ['pricing-analysis', 'Pricing Analyst', 'Senior', 'SaaS / Any', 'Conducts pricing analysis.'],
    ['pricing-calculator', 'Pricing Calculator Builder', 'Mid-Level', 'SaaS / Any', 'Builds interactive pricing calculators.'],
    ['pricing-strategy', 'Pricing Strategist', 'Senior', 'SaaS / Any', 'Develops pricing strategies.'],
    ['profit-loss-report', 'P&L Reporting Manager', 'Senior', 'SaaS / Any', 'Produces profit and loss reports.'],
    ['quarterly-review', 'QBR Lead', 'Senior', 'SaaS / Any', 'Facilitates quarterly business reviews.'],
    ['rate-negotiation-script', 'Rate Negotiation Coach', 'Mid-Level', 'Consulting / Agency', 'Develops rate negotiation scripts.'],
    ['revenue-forecast', 'Revenue Forecasting Analyst', 'Senior', 'SaaS / Any', 'Builds revenue forecasts.'],
    ['roi-calculator', 'ROI Calculator Builder', 'Mid-Level', 'SaaS / Any', 'Creates ROI calculators.'],
    ['subscription-metrics', 'Subscription Metrics Analyst', 'Senior', 'SaaS', 'Tracks subscription metrics.'],
    ['tax-deduction-finder', 'Tax Deduction Specialist', 'Mid-Level', 'Any', 'Identifies tax deductions.'],
    ['tax-prep-checklist', 'Tax Prep Coordinator', 'Mid-Level', 'Any', 'Manages tax preparation checklists.'],
    ['unit-economics', 'Unit Economics Analyst', 'Senior', 'SaaS / Any', 'Calculates unit economics.'],
  ]),

  // ── HR (28) ──
  ...buildSkillsFromList('hr', '.agents/skills/HR & Team', [
    ['annual-review', 'Performance Review Admin', 'Mid-Level', 'SaaS / Any', 'Manages annual performance review cycles.'],
    ['benefits-guide', 'Benefits Administrator', 'Mid-Level', 'SaaS / Any', 'Creates benefits guides.'],
    ['contractor-brief', 'Contractor Manager', 'Mid-Level', 'SaaS / Any', 'Manages contractor engagements.'],
    ['culture-document', 'Culture Lead', 'Senior', 'SaaS / Any', 'Defines company culture documents.'],
    ['diversity-policy', 'DEI Program Manager', 'Senior', 'SaaS / Any', 'Develops diversity and inclusion policies.'],
    ['employee-handbook', 'Employee Handbook Owner', 'Senior', 'SaaS / Any', 'Creates employee handbooks.'],
    ['employee-survey', 'Engagement Analyst', 'Mid-Level', 'SaaS / Any', 'Designs employee engagement surveys.'],
    ['exit-interview-template', 'Exit Interview Coordinator', 'Mid-Level', 'SaaS / Any', 'Conducts exit interviews.'],
    ['freelancer-management', 'Freelancer Ops Manager', 'Mid-Level', 'SaaS / Any', 'Manages freelancer pools.'],
    ['hiring-scorecard', 'Hiring Manager', 'Mid-Level', 'SaaS / Any', 'Creates hiring scorecards.'],
    ['interview-question-bank', 'Interview Designer', 'Mid-Level', 'SaaS / Any', 'Builds interview question banks.'],
    ['job-posting', 'Talent Acquisition Specialist', 'Mid-Level', 'SaaS / Any', 'Writes job postings.'],
    ['mentorship-program', 'Mentorship Director', 'Senior', 'SaaS / Any', 'Designs mentorship programs.'],
    ['offboarding-checklist', 'Offboarding Coordinator', 'Mid-Level', 'SaaS / Any', 'Manages offboarding processes.'],
    ['offer-letter', 'Offer Letter Writer', 'Mid-Level', 'SaaS / Any', 'Drafts offer letters.'],
    ['okr-builder', 'OKR Program Manager', 'Senior', 'SaaS / Any', 'Implements OKR frameworks.'],
    ['onboarding-checklist', 'Onboarding Program Manager', 'Mid-Level', 'SaaS / Any', 'Designs new hire onboarding.'],
    ['one-on-one-template', '1:1 Meeting Facilitator', 'Mid-Level', 'SaaS / Any', 'Creates 1:1 meeting frameworks.'],
    ['performance-review', 'Performance Management Lead', 'Senior', 'SaaS / Any', 'Designs performance review processes.'],
    ['pip-template', 'PIP Manager', 'Senior', 'SaaS / Any', 'Creates performance improvement plans.'],
    ['referral-bonus-plan', 'Referral Program Coordinator', 'Mid-Level', 'SaaS / Any', 'Designs employee referral programs.'],
    ['remote-team-handbook', 'Remote Work Handbook Owner', 'Senior', 'SaaS / Any', 'Creates remote team handbooks.'],
    ['remote-work-policy', 'Remote Work Policy Designer', 'Senior', 'SaaS / Any', 'Develops remote work policies.'],
    ['succession-plan', 'Succession Planning Lead', 'Senior', 'SaaS / Any', 'Creates succession plans.'],
    ['team-building-plan', 'Team Building Coordinator', 'Mid-Level', 'SaaS / Any', 'Plans team building activities.'],
    ['team-charter', 'Team Charter Facilitator', 'Senior', 'SaaS / Any', 'Facilitates team charter creation.'],
    ['training-manual', 'Training Manual Author', 'Mid-Level', 'SaaS / Any', 'Writes training manuals.'],
    ['training-plan', 'Training Program Designer', 'Mid-Level', 'SaaS / Any', 'Designs training plans.'],
  ]),

  // ── Industry-Specific (15) ──
  ...buildSkillsFromList('industry', '.agents/skills/Industry-Specific', [
    ['api-documentation', 'API Documentation Writer', 'Senior', 'SaaS / Tech', 'Writes API documentation.'],
    ['health-disclaimer', 'Health Disclaimer Writer', 'Mid-Level', 'Health / Wellness', 'Writes health disclaimers.'],
    ['no-code-app-plan', 'No-Code Solutions Architect', 'Mid-Level', 'SaaS / Tech', 'Plans no-code application builds.'],
    ['platform-help-center', 'Help Center Manager', 'Mid-Level', 'SaaS / Marketplace', 'Builds platform help centers.'],
    ['platform-partnership', 'Platform Partnership Manager', 'Senior', 'SaaS / Marketplace', 'Develops platform partnerships.'],
    ['platform-trust-system', 'Trust & Safety Lead', 'Senior', 'SaaS / Marketplace', 'Designs trust and safety systems.'],
    ['restaurant-marketing-plan', 'Restaurant Marketing Manager', 'Mid-Level', 'Restaurant / Food', 'Creates restaurant marketing plans.'],
    ['restaurant-review-response', 'Review Response Specialist', 'Junior', 'Restaurant / Food', 'Writes professional review responses.'],
    ['restaurant-sop', 'Restaurant Operations Manager', 'Mid-Level', 'Restaurant / Food', 'Develops restaurant SOPs.'],
    ['seasonal-menu-plan', 'Menu Planner', 'Mid-Level', 'Restaurant / Food', 'Plans seasonal menu rotations.'],
    ['saas-evaluation', 'SaaS Evaluation Analyst', 'Mid-Level', 'SaaS', 'Evaluates SaaS tools.'],
    ['supplement-disclaimer', 'Supplement Disclaimer Writer', 'Mid-Level', 'Health / Wellness', 'Writes supplement disclaimers.'],
    ['tech-stack-recommendation', 'Tech Stack Architect', 'Senior', 'SaaS / Tech', 'Evaluates and recommends technology stacks.'],
    ['tenant-screening-checklist', 'Tenant Screening Specialist', 'Mid-Level', 'Real Estate', 'Creates tenant screening checklists.'],
    ['tool-stack-audit', 'Tool Stack Auditor', 'Senior', 'SaaS / Any', 'Audits tool stacks for optimization.'],
  ]),

  // ── Customer Success (24) ──
  ...buildSkillsFromList('customer-success', '.agents/skills/Launch & Growth', [
    ['annual-report-writer', 'Annual Report Writer', 'Senior', 'SaaS / Any', 'Writes annual reports.'],
    ['chatbot-script', 'Chatbot Designer', 'Mid-Level', 'SaaS / Any', 'Designs chatbot conversation flows.'],
    ['churn-analysis', 'Churn Analyst', 'Senior', 'SaaS', 'Analyzes churn patterns.'],
    ['churn-prevention-playbook', 'Churn Prevention Strategist', 'Senior', 'SaaS', 'Creates churn prevention playbooks.'],
    ['complaint-resolution', 'Complaint Resolution Specialist', 'Mid-Level', 'SaaS / Any', 'Designs complaint resolution processes.'],
    ['customer-advisory-board', 'Customer Advisory Board Manager', 'Senior', 'SaaS', 'Builds customer advisory boards.'],
    ['customer-health-score', 'Customer Health Score Designer', 'Senior', 'SaaS', 'Designs customer health scoring models.'],
    ['customer-success-playbook', 'CS Playbook Owner', 'Senior', 'SaaS', 'Creates customer success playbooks.'],
    ['customer-support-kb', 'Knowledge Base Builder', 'Mid-Level', 'SaaS', 'Builds support knowledge bases.'],
    ['customer-win-story', 'Customer Win Story Writer', 'Mid-Level', 'SaaS / Any', 'Documents customer success stories.'],
    ['feature-request-system', 'Feature Request Manager', 'Mid-Level', 'SaaS', 'Builds feature request tracking systems.'],
    ['nps-survey', 'NPS Survey Manager', 'Mid-Level', 'SaaS / Any', 'Designs and manages NPS surveys.'],
    ['onboarding-flow', 'Onboarding Flow Designer', 'Senior', 'SaaS', 'Designs product onboarding flows.'],
    ['product-feedback-loop', 'Product Feedback Manager', 'Senior', 'SaaS', 'Creates closed-loop feedback systems.'],
    ['review-response', 'Review Response Manager', 'Mid-Level', 'SaaS / Any', 'Manages review responses.'],
    ['saas-cancellation-flow', 'Cancellation Flow Designer', 'Mid-Level', 'SaaS', 'Designs SaaS cancellation flows.'],
    ['saas-onboarding-flow', 'SaaS Onboarding Architect', 'Senior', 'SaaS', 'Architects SaaS onboarding flows.'],
    ['satisfaction-survey', 'Satisfaction Survey Designer', 'Mid-Level', 'SaaS / Any', 'Designs CSAT surveys.'],
    ['self-service-portal', 'Self-Service Portal Designer', 'Mid-Level', 'SaaS', 'Designs self-service portals.'],
    ['service-level-agreement', 'SLA Manager', 'Senior', 'SaaS', 'Defines service level agreements.'],
    ['service-recovery-plan', 'Service Recovery Lead', 'Senior', 'SaaS / Any', 'Creates service recovery plans.'],
    ['support-response-templates', 'Support Template Writer', 'Mid-Level', 'SaaS', 'Writes support response templates.'],
    ['user-research-plan', 'User Research Lead', 'Senior', 'SaaS', 'Designs user research plans.'],
    ['voice-of-customer', 'VoC Program Manager', 'Senior', 'SaaS', 'Manages Voice of Customer programs.'],
  ]),

  // ── Legal (30) ──
  ...buildSkillsFromList('legal', '.agents/skills/Legal & Compliance', [
    ['accessibility-policy', 'Accessibility Specialist', 'Senior', 'SaaS / Any', 'Develops accessibility policies.'],
    ['cease-and-desist', 'Litigation Support', 'Senior', 'Any', 'Drafts cease-and-desist letters.'],
    ['client-agreement', 'Client Agreement Writer', 'Mid-Level', 'SaaS / Agency', 'Drafts client service agreements.'],
    ['compliance-checklist', 'Compliance Officer', 'Senior', 'SaaS / Any', 'Creates compliance checklists.'],
    ['contract-writer', 'Contract Writer', 'Senior', 'SaaS / Any', 'Drafts commercial contracts.'],
    ['cookie-policy', 'Cookie Policy Specialist', 'Mid-Level', 'SaaS / Any', 'Creates cookie policies.'],
    ['copyright-notice', 'Copyright Administrator', 'Mid-Level', 'SaaS / Any', 'Manages copyright notices.'],
    ['data-processing-agreement', 'DPA Manager', 'Senior', 'SaaS / Any', 'Drafts data processing agreements.'],
    ['disclaimer-generator', 'Disclaimer Writer', 'Mid-Level', 'SaaS / Any', 'Creates legal disclaimers.'],
    ['expense-policy', 'Expense Policy Writer', 'Mid-Level', 'SaaS / Any', 'Writes expense policies.'],
    ['gdpr-compliance-checklist', 'GDPR Compliance Manager', 'Senior', 'SaaS / Any', 'Manages GDPR compliance.'],
    ['independent-contractor-agreement', 'Contractor Agreement Writer', 'Mid-Level', 'SaaS / Any', 'Drafts contractor agreements.'],
    ['intellectual-property-audit', 'IP Auditor', 'Senior', 'SaaS / Any', 'Conducts IP audits.'],
    ['letter-of-intent', 'LOI Writer', 'Mid-Level', 'SaaS / Any', 'Drafts letters of intent.'],
    ['licensing-agreement', 'Licensing Manager', 'Senior', 'SaaS / Any', 'Drafts licensing agreements.'],
    ['nda-template', 'NDA Writer', 'Mid-Level', 'SaaS / Any', 'Creates NDA templates.'],
    ['non-compete-agreement', 'Non-Compete Writer', 'Mid-Level', 'SaaS / Any', 'Drafts non-compete agreements.'],
    ['partnership-agreement', 'Partnership Agreement Writer', 'Senior', 'SaaS / Any', 'Drafts partnership agreements.'],
    ['payment-terms-policy', 'Payment Terms Writer', 'Mid-Level', 'SaaS / Any', 'Creates payment terms policies.'],
    ['privacy-policy', 'Privacy Policy Writer', 'Senior', 'SaaS / Any', 'Writes privacy policies.'],
    ['retainer-agreement', 'Retainer Agreement Writer', 'Mid-Level', 'SaaS / Agency', 'Drafts retainer agreements.'],
    ['return-policy', 'Return Policy Writer', 'Mid-Level', 'E-commerce / SaaS', 'Creates return policies.'],
    ['saas-agreement', 'SaaS Agreement Specialist', 'Senior', 'SaaS', 'Drafts SaaS subscription agreements.'],
    ['shipping-policy', 'Shipping Policy Writer', 'Mid-Level', 'E-commerce', 'Creates shipping policies.'],
    ['subcontractor-agreement', 'Subcontractor Agreement Writer', 'Mid-Level', 'SaaS / Any', 'Drafts subcontractor agreements.'],
    ['terms-of-service', 'Terms of Service Writer', 'Senior', 'SaaS / Any', 'Writes terms of service.'],
    ['terms-of-use-app', 'App Terms of Use Writer', 'Senior', 'SaaS / App', 'Creates app terms of use.'],
    ['trademark-application', 'Trademark Specialist', 'Senior', 'SaaS / Any', 'Manages trademark applications.'],
    ['waiver-release', 'Waiver Writer', 'Mid-Level', 'Events / Any', 'Drafts waivers and liability releases.'],
    ['workplace-policy', 'Workplace Policy Writer', 'Senior', 'SaaS / Any', 'Creates workplace policies.'],
  ]),

  // ── Community (2) ──
  ...buildSkillsFromList('community', '.agents/skills/Nonprofit & Community', [
    ['nonprofit-fundraising-letter', 'Fundraising Letter Writer', 'Mid-Level', 'Nonprofit / Any', 'Writes nonprofit fundraising letters.'],
    ['volunteer-recruitment', 'Volunteer Recruitment Coordinator', 'Mid-Level', 'Nonprofit / Any', 'Designs volunteer recruitment programs.'],
  ]),

  // ── Operations (30) ──
  ...buildSkillsFromList('operations', '.agents/skills/Operations & Systems', [
    ['annual-planning', 'Annual Planning Lead', 'Senior', 'SaaS / Any', 'Facilitates annual planning processes.'],
    ['batch-processing-system', 'Batch Processing Engineer', 'Senior', 'SaaS / Tech', 'Designs batch processing systems.'],
    ['business-continuity-plan', 'Business Continuity Planner', 'Senior', 'SaaS / Any', 'Creates business continuity plans.'],
    ['change-management-plan', 'Change Management Lead', 'Senior', 'SaaS / Any', 'Develops change management plans.'],
    ['client-crm', 'CRM Administrator', 'Mid-Level', 'SaaS / Any', 'Configures CRM systems.'],
    ['decision-matrix', 'Decision Support Analyst', 'Mid-Level', 'SaaS / Any', 'Builds decision matrices.'],
    ['delegation-framework', 'Delegation Framework Designer', 'Senior', 'SaaS / Any', 'Creates delegation frameworks.'],
    ['energy-management', 'Productivity Coach', 'Mid-Level', 'Any', 'Designs energy management frameworks.'],
    ['escalation-procedure', 'Escalation Procedure Owner', 'Senior', 'SaaS / Any', 'Defines escalation procedures.'],
    ['fulfillment-sop', 'Fulfillment Operations Manager', 'Mid-Level', 'E-commerce / Any', 'Creates fulfillment SOPs.'],
    ['inventory-management', 'Inventory Manager', 'Mid-Level', 'E-commerce / Any', 'Manages inventory systems.'],
    ['knowledge-base-builder', 'Knowledge Base Architect', 'Mid-Level', 'SaaS / Any', 'Designs internal knowledge bases.'],
    ['meeting-agenda', 'Meeting Facilitator', 'Mid-Level', 'SaaS / Any', 'Creates structured meeting agendas.'],
    ['meeting-notes', 'Meeting Notes Coordinator', 'Junior', 'SaaS / Any', 'Takes and distributes meeting notes.'],
    ['morning-routine-builder', 'Routine Optimization Coach', 'Mid-Level', 'Any', 'Designs morning routines.'],
    ['process-automation-audit', 'Process Automation Auditor', 'Senior', 'SaaS / Any', 'Audits processes for automation.'],
    ['project-tracker', 'Project Tracker Manager', 'Mid-Level', 'SaaS / Any', 'Sets up project tracking systems.'],
    ['quality-assurance-checklist', 'QA Checklist Manager', 'Mid-Level', 'SaaS / Any', 'Creates QA checklists.'],
    ['report-automation', 'Report Automation Engineer', 'Mid-Level', 'SaaS / Any', 'Automates recurring reports.'],
    ['retrospective', 'Retrospective Facilitator', 'Mid-Level', 'SaaS / Any', 'Facilitates team retrospectives.'],
    ['risk-assessment', 'Risk Assessment Analyst', 'Senior', 'SaaS / Any', 'Conducts risk assessments.'],
    ['scope-of-work', 'Scope of Work Writer', 'Mid-Level', 'SaaS / Agency', 'Writes scope of work documents.'],
    ['sop-builder', 'SOP Builder', 'Mid-Level', 'SaaS / Any', 'Creates standard operating procedures.'],
    ['status-update-template', 'Status Update Writer', 'Mid-Level', 'SaaS / Any', 'Creates status update templates.'],
    ['task-prioritization', 'Task Prioritization Specialist', 'Mid-Level', 'SaaS / Any', 'Implements prioritization frameworks.'],
    ['time-audit', 'Time Audit Analyst', 'Mid-Level', 'SaaS / Any', 'Conducts time audits.'],
    ['vendor-evaluation', 'Vendor Evaluation Analyst', 'Mid-Level', 'SaaS / Any', 'Evaluates vendors.'],
    ['vendor-onboarding', 'Vendor Onboarding Specialist', 'Mid-Level', 'SaaS / Any', 'Manages vendor onboarding.'],
    ['weekly-report', 'Weekly Report Writer', 'Mid-Level', 'SaaS / Any', 'Produces weekly reports.'],
    ['workflow-mapper', 'Workflow Architect', 'Senior', 'SaaS / Any', 'Maps and optimizes business workflows.'],
  ]),

  // ── SEO (20) ──
  ...buildSkillsFromList('seo', '.agents/skills/SEO & Search', [
    ['checkout-optimizer', 'Checkout Optimization Specialist', 'Mid-Level', 'E-commerce / SaaS', 'Optimizes checkout flows.'],
    ['featured-snippet-optimizer', 'Featured Snippet Optimizer', 'Mid-Level', 'SaaS / Any', 'Optimizes content for featured snippets.'],
    ['google-business-profile', 'Google Business Profile Manager', 'Mid-Level', 'Local / Any', 'Manages Google Business Profiles.'],
    ['keyword-research', 'Keyword Research Specialist', 'Mid-Level', 'SaaS / Any', 'Conducts keyword research.'],
    ['landing-page-audit', 'Landing Page Auditor', 'Senior', 'SaaS / Any', 'Audits landing pages for conversion.'],
    ['link-building-plan', 'Link Building Strategist', 'Senior', 'SaaS / Any', 'Develops link building strategies.'],
    ['local-seo-plan', 'Local SEO Specialist', 'Mid-Level', 'Local / Any', 'Creates local SEO plans.'],
    ['marketplace-seo', 'Marketplace SEO Specialist', 'Mid-Level', 'Marketplace / E-commerce', 'Optimizes marketplace listings for search.'],
    ['meta-tag-optimizer', 'Meta Tag Optimizer', 'Mid-Level', 'SaaS / Any', 'Writes and optimizes meta tags.'],
    ['platform-migration', 'Platform Migration SEO Lead', 'Senior', 'SaaS / Any', 'Manages SEO during platform migrations.'],
    ['product-listing-optimizer', 'Product Listing Optimizer', 'Mid-Level', 'E-commerce', 'Optimizes product listings for search.'],
    ['schema-markup-guide', 'Schema Markup Specialist', 'Mid-Level', 'SaaS / Any', 'Implements structured data markup.'],
    ['seo-audit', 'SEO Audit Lead', 'Senior', 'SaaS / Any', 'Conducts comprehensive SEO audits.'],
    ['seo-competitor-analysis', 'SEO Competitive Analyst', 'Mid-Level', 'SaaS / Any', 'Analyzes competitor SEO strategies.'],
    ['seo-migration-plan', 'SEO Migration Specialist', 'Senior', 'SaaS / Any', 'Plans SEO migration strategies.'],
    ['seo-reporting-template', 'SEO Reporting Analyst', 'Mid-Level', 'SaaS / Any', 'Creates SEO reporting templates.'],
    ['site-architecture-plan', 'Information Architect', 'Senior', 'SaaS / Any', 'Plans site architecture for SEO.'],
    ['store-page-audit', 'Store Page Auditor', 'Mid-Level', 'E-commerce', 'Audits e-commerce store pages.'],
    ['technical-seo-checklist', 'Technical SEO Lead', 'Senior', 'SaaS / Any', 'Manages technical SEO.'],
    ['youtube-seo', 'YouTube SEO Specialist', 'Mid-Level', 'SaaS / Any', 'Optimizes YouTube content for search.'],
  ]),

  // ── Sales (8) ──
  ...buildSkillsFromList('sales', '.agents/skills/Sales & Funnels', [
    ['business-plan', 'Business Plan Writer', 'Senior', 'SaaS / Any', 'Writes comprehensive business plans.'],
    ['coaching-framework', 'Coaching Framework Designer', 'Senior', 'Consulting / Education', 'Designs coaching frameworks.'],
    ['collaboration-agreement', 'Collaboration Agreement Writer', 'Mid-Level', 'SaaS / Any', 'Drafts collaboration agreements.'],
    ['competitor-analysis', 'Competitive Intelligence Lead', 'Senior', 'SaaS / Any', 'Conducts competitor analysis.'],
    ['customer-journey-map', 'Customer Journey Mapper', 'Senior', 'SaaS / Any', 'Maps customer journeys.'],
    ['customer-persona', 'Customer Persona Developer', 'Senior', 'SaaS / Any', 'Creates data-driven customer personas.'],
    ['customer-segmentation', 'Segmentation Analyst', 'Senior', 'SaaS / Any', 'Develops customer segmentation models.'],
    ['discovery-call-script', 'SDR', 'Mid-Level', 'SaaS / B2B', 'Writes discovery call scripts.'],
  ]),

  // ── Social Media (38) ──
  ...buildSkillsFromList('social-media', '.agents/skills/Social Media', [
    ['author-platform-plan', 'Author Platform Strategist', 'Mid-Level', 'Any', 'Builds author platform strategies.'],
    ['brand-photography-brief', 'Brand Photography Director', 'Mid-Level', 'SaaS / Any', 'Creates brand photography briefs.'],
    ['co-marketing-plan', 'Co-Marketing Manager', 'Senior', 'SaaS / Any', 'Develops co-marketing plans.'],
    ['community-launch', 'Community Launch Manager', 'Senior', 'SaaS / Any', 'Plans community launches.'],
    ['community-moderation', 'Community Moderator Lead', 'Mid-Level', 'SaaS / Any', 'Designs community moderation systems.'],
    ['crisis-comms', 'Crisis Communications Manager', 'Senior', 'SaaS / Any', 'Manages crisis communications.'],
    ['facebook-group-plan', 'Facebook Group Manager', 'Mid-Level', 'SaaS / Any', 'Plans Facebook group strategies.'],
    ['food-photography-brief', 'Food Photography Director', 'Mid-Level', 'Food / Lifestyle', 'Creates food photography briefs.'],
    ['guest-post-pitch', 'Guest Post Outreach Specialist', 'Mid-Level', 'SaaS / Any', 'Pitches guest post opportunities.'],
    ['hashtag-strategy', 'Hashtag Strategist', 'Mid-Level', 'SaaS / Any', 'Develops hashtag strategies.'],
    ['influencer-campaign-brief', 'Influencer Campaign Manager', 'Senior', 'SaaS / Any', 'Creates influencer campaign briefs.'],
    ['influencer-outreach', 'Influencer Outreach Specialist', 'Mid-Level', 'SaaS / Any', 'Manages influencer outreach.'],
    ['instagram-carousel', 'Instagram Content Strategist', 'Mid-Level', 'SaaS / Any', 'Creates Instagram carousel strategies.'],
    ['linkedin-profile-optimizer', 'LinkedIn Profile Optimizer', 'Mid-Level', 'SaaS / B2B', 'Optimizes LinkedIn profiles.'],
    ['linkedin-strategy', 'LinkedIn Strategy Lead', 'Senior', 'SaaS / B2B', 'Develops LinkedIn marketing strategies.'],
    ['media-kit', 'Media Kit Designer', 'Mid-Level', 'SaaS / Any', 'Creates media kits.'],
    ['meme-content-brief', 'Meme Content Creator', 'Junior', 'SaaS / Any', 'Creates meme content briefs.'],
    ['menu-design-brief', 'Menu Design Director', 'Mid-Level', 'Restaurant / Food', 'Creates menu design briefs.'],
    ['networking-strategy', 'Networking Strategist', 'Senior', 'SaaS / Any', 'Develops networking strategies.'],
    ['personal-brand-strategy', 'Personal Brand Strategist', 'Senior', 'SaaS / Any', 'Builds personal brand strategies.'],
    ['pinterest-strategy', 'Pinterest Strategist', 'Mid-Level', 'SaaS / Any', 'Develops Pinterest strategies.'],
    ['platform-community-guidelines', 'Community Guidelines Writer', 'Mid-Level', 'SaaS / Marketplace', 'Writes community guidelines.'],
    ['podcast-guest-pitch', 'Podcast Guest Outreach', 'Mid-Level', 'SaaS / Any', 'Pitches podcast guest opportunities.'],
    ['pr-pitch', 'PR Specialist', 'Mid-Level', 'SaaS / Any', 'Writes PR pitches.'],
    ['product-photography-brief', 'Product Photography Director', 'Mid-Level', 'E-commerce / Any', 'Creates product photography briefs.'],
    ['reddit-strategy', 'Reddit Strategy Specialist', 'Mid-Level', 'SaaS / Any', 'Develops Reddit engagement strategies.'],
    ['short-form-video-plan', 'Short-Form Video Strategist', 'Mid-Level', 'SaaS / Any', 'Plans short-form video content.'],
    ['social-listening-plan', 'Social Listening Analyst', 'Mid-Level', 'SaaS / Any', 'Creates social listening plans.'],
    ['social-media-audit', 'Social Media Auditor', 'Senior', 'SaaS / Any', 'Conducts social media audits.'],
    ['social-media-calendar', 'Social Calendar Manager', 'Mid-Level', 'SaaS / Any', 'Plans social media content calendars.'],
    ['social-media-graphics', 'Social Media Graphic Designer', 'Mid-Level', 'SaaS / Any', 'Creates social media graphics.'],
    ['social-media-policy', 'Social Media Policy Owner', 'Senior', 'SaaS / Any', 'Writes social media policies.'],
    ['social-media-strategy', 'Social Media Strategy Director', 'Senior', 'SaaS / Any', 'Develops social media strategies.'],
    ['sponsor-pitch', 'Sponsorship Outreach Specialist', 'Mid-Level', 'SaaS / Any', 'Writes sponsorship pitches.'],
    ['thread-hook-writer', 'Thread & Hook Writer', 'Mid-Level', 'SaaS / Any', 'Writes viral thread hooks.'],
    ['tiktok-script', 'TikTok Content Creator', 'Mid-Level', 'SaaS / Any', 'Writes TikTok scripts.'],
    ['twitter-thread', 'Twitter/X Thread Writer', 'Mid-Level', 'SaaS / Any', 'Creates Twitter/X threads.'],
    ['youtube-strategy', 'YouTube Strategy Lead', 'Senior', 'SaaS / Any', 'Develops YouTube channel strategies.'],
  ]),

  // ── Strategy (1) ──
  { dept_slug: 'strategy', slug: 'project-planning', name: 'Project Planning Lead', seniority: 'Senior', company_type: 'SaaS / Any', description: 'Leads project planning, converting ideas into technical handoffs and business proposals.', skills_path: '.agents/skills/project-planning/' },
];

// ── Helper to build skills from compact list ──

function buildSkillsFromList(
  deptSlug: string,
  basePath: string,
  items: [string, string, string, string, string][],
): SkillSeed[] {
  return items.map(([slug, name, seniority, companyType, description]) => ({
    dept_slug: deptSlug,
    slug,
    name,
    seniority,
    company_type: companyType,
    description,
    skills_path: `${basePath}/${slug}`,
  }));
}

// ── Seed Function ────────────────────────────────────────────────────────────

export async function seedDepartmentRoles(): Promise<void> {
  console.log('[seed] Seeding department roles and skills...');

  // Upsert department roles
  for (const dept of DEPT_ROLES) {
    const { error } = await supabase.from('department_roles').upsert(
      {
        slug: dept.slug,
        name: dept.name,
        short_name: dept.short_name,
        dept_index: dept.dept_index,
        description: dept.description,
        system_prompt: dept.system_prompt,
        default_skills: dept.default_skills,
        rules: dept.rules,
        model_tier: dept.model_tier,
        default_budget: dept.default_budget,
        tool_access: dept.tool_access,
        color: dept.color,
        sprite_index: dept.sprite_index,
        mcp_servers: dept.mcp_servers,
        source: 'builtin',
      },
      { onConflict: 'slug' },
    );
    if (error) console.error(`[seed] Failed to upsert dept ${dept.slug}:`, error.message);
  }

  // Load dept role IDs for linking skills
  const { data: deptRows } = await supabase.from('department_roles').select('id, slug');
  const deptMap = new Map((deptRows ?? []).map((d: any) => [d.slug, d.id]));

  // Guard: if most departments failed to create, skip skill seeding
  if (deptMap.size < Math.floor(DEPT_ROLES.length * 0.5)) {
    console.error(`[seed] Only ${deptMap.size}/${DEPT_ROLES.length} departments created. Aborting skill seeding.`);
    return;
  }

  // Upsert skills
  let count = 0;
  for (const skill of ALL_SKILLS) {
    const deptRoleId = deptMap.get(skill.dept_slug);
    if (!deptRoleId) {
      console.error(`[seed] No dept found for ${skill.dept_slug}, skipping ${skill.slug}`);
      continue;
    }

    const { error } = await supabase.from('agent_skills').upsert(
      {
        dept_role_id: deptRoleId,
        slug: skill.slug,
        name: skill.name,
        seniority: skill.seniority,
        company_type: skill.company_type,
        description: skill.description,
        skills_path: skill.skills_path,
      },
      { onConflict: 'slug' },
    );
    if (error) console.error(`[seed] Failed to upsert skill ${skill.slug}:`, error.message);
    else count++;
  }

  console.log(`[seed] Done — ${DEPT_ROLES.length} departments, ${count} skills seeded.`);
}

export { DEPT_ROLES, ALL_SKILLS };
